// Code generated by "stringer -type=Format -trimprefix=Format"; DO NOT EDIT.

package loge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatJSON-0]
	_ = x[FormatText-1]
	_ = x[FormatTint-2]
}

const _Format_name = "JSONTextTint"

var _Format_index = [...]uint8{0, 4, 8, 12}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
