// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: runtime/middlewares/cors.proto

package middlewares

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CorsConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CorsConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CorsConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CorsConfigMultiError, or
// nil if none found.
func (m *CorsConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *CorsConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	// no validation rules for AllowCredentials

	if all {
		switch v := interface{}(m.GetMaxAge()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CorsConfigValidationError{
					field:  "MaxAge",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CorsConfigValidationError{
					field:  "MaxAge",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMaxAge()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CorsConfigValidationError{
				field:  "MaxAge",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AllowWildcard

	// no validation rules for AllowBrowserExtensions

	// no validation rules for AllowWebSockets

	// no validation rules for AllowPrivateNetwork

	// no validation rules for AllowFiles

	if len(errors) > 0 {
		return CorsConfigMultiError(errors)
	}

	return nil
}

// CorsConfigMultiError is an error wrapping multiple validation errors
// returned by CorsConfig.ValidateAll() if the designated constraints aren't met.
type CorsConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CorsConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CorsConfigMultiError) AllErrors() []error { return m }

// CorsConfigValidationError is the validation error returned by
// CorsConfig.Validate if the designated constraints aren't met.
type CorsConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CorsConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CorsConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CorsConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CorsConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CorsConfigValidationError) ErrorName() string { return "CorsConfigValidationError" }

// Error satisfies the builtin error interface
func (e CorsConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCorsConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CorsConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CorsConfigValidationError{}
