// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config/v1/data.proto

package config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DataConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DataConfigMultiError, or
// nil if none found.
func (m *DataConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *DataConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DataConfigMultiError(errors)
	}

	return nil
}

// DataConfigMultiError is an error wrapping multiple validation errors
// returned by DataConfig.ValidateAll() if the designated constraints aren't met.
type DataConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataConfigMultiError) AllErrors() []error { return m }

// DataConfigValidationError is the validation error returned by
// DataConfig.Validate if the designated constraints aren't met.
type DataConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataConfigValidationError) ErrorName() string { return "DataConfigValidationError" }

// Error satisfies the builtin error interface
func (e DataConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataConfigValidationError{}

// Validate checks the field values on DataConfig_Database with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DataConfig_Database) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataConfig_Database with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DataConfig_DatabaseMultiError, or nil if none found.
func (m *DataConfig_Database) ValidateAll() error {
	return m.validate(true)
}

func (m *DataConfig_Database) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Debug

	// no validation rules for Driver

	// no validation rules for Source

	// no validation rules for Migrate

	// no validation rules for EnableTrace

	// no validation rules for EnableMetrics

	// no validation rules for MaxIdleConnections

	// no validation rules for MaxOpenConnections

	if all {
		switch v := interface{}(m.GetConnectionMaxLifetime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DataConfig_DatabaseValidationError{
					field:  "ConnectionMaxLifetime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DataConfig_DatabaseValidationError{
					field:  "ConnectionMaxLifetime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConnectionMaxLifetime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DataConfig_DatabaseValidationError{
				field:  "ConnectionMaxLifetime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DataConfig_DatabaseMultiError(errors)
	}

	return nil
}

// DataConfig_DatabaseMultiError is an error wrapping multiple validation
// errors returned by DataConfig_Database.ValidateAll() if the designated
// constraints aren't met.
type DataConfig_DatabaseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataConfig_DatabaseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataConfig_DatabaseMultiError) AllErrors() []error { return m }

// DataConfig_DatabaseValidationError is the validation error returned by
// DataConfig_Database.Validate if the designated constraints aren't met.
type DataConfig_DatabaseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataConfig_DatabaseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataConfig_DatabaseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataConfig_DatabaseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataConfig_DatabaseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataConfig_DatabaseValidationError) ErrorName() string {
	return "DataConfig_DatabaseValidationError"
}

// Error satisfies the builtin error interface
func (e DataConfig_DatabaseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataConfig_Database.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataConfig_DatabaseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataConfig_DatabaseValidationError{}
