// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config/v1/tracer.proto

package config

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TraceConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TraceConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TraceConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TraceConfigMultiError, or
// nil if none found.
func (m *TraceConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *TraceConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Endpoint

	if len(errors) > 0 {
		return TraceConfigMultiError(errors)
	}

	return nil
}

// TraceConfigMultiError is an error wrapping multiple validation errors
// returned by TraceConfig.ValidateAll() if the designated constraints aren't met.
type TraceConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TraceConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TraceConfigMultiError) AllErrors() []error { return m }

// TraceConfigValidationError is the validation error returned by
// TraceConfig.Validate if the designated constraints aren't met.
type TraceConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TraceConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TraceConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TraceConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TraceConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TraceConfigValidationError) ErrorName() string { return "TraceConfigValidationError" }

// Error satisfies the builtin error interface
func (e TraceConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTraceConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TraceConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TraceConfigValidationError{}
