// Code generated by "stringer -type=TokenType -trimprefix=ContextType -output=security_string.go"; DO NOT EDIT.

package security

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContextTypeContext-0]
	_ = x[ContextTypeHeader-1]
	_ = x[ContextTypeMetadata-2]
	_ = x[ContextTypeQuery-3]
	_ = x[ContextTypeCookie-4]
	_ = x[ContextTypeParam-5]
	_ = x[ContextTypeForm-6]
	_ = x[ContextTypeBody-7]
	_ = x[ContextTypeSession-8]
	_ = x[ContextTypeUnknown-9]
}

const _TokenType_name = "ContextHeaderMetadataQueryCookieParamFormBodySessionUnknown"

var _TokenType_index = [...]uint8{0, 7, 13, 21, 26, 32, 37, 41, 45, 52, 59}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
