blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Share an Idea
    url: https://github.com/orgs/origadmin/discussions/new/choose
    about: Please use GitHub Discussions for questions, ideas, and general conversation.
