// Code generated by "stringer -type=TokenSource -trimprefix=TokenSource -output=security_string.go"; DO NOT EDIT.

package security

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenSourceContext-0]
	_ = x[TokenSourceHeader-1]
	_ = x[TokenSourceClientHeader-2]
	_ = x[TokenSourceServerHeader-3]
	_ = x[TokenSourceMetadata-4]
	_ = x[TokenSourceMetadataClient-5]
	_ = x[TokenSourceMetadataServer-6]
	_ = x[TokenSourceQueryParameter-7]
	_ = x[TokenSourceCookie-8]
	_ = x[TokenSourceURLParameter-9]
	_ = x[TokenSourceForm-10]
	_ = x[TokenSourceRequestBody-11]
	_ = x[TokenSourceSession-12]
	_ = x[TokenSourceUnknown-13]
}

const _TokenSource_name = "ContextHeaderClientHeaderServerHeaderMetadataMetadataClientMetadataServerQueryParameterCookieURLParameterFormRequestBodySessionUnknown"

var _TokenSource_index = [...]uint8{0, 7, 13, 25, 37, 45, 59, 73, 87, 93, 105, 109, 120, 127, 134}

func (i TokenSource) String() string {
	if i < 0 || i >= TokenSource(len(_TokenSource_index)-1) {
		return "TokenSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenSource_name[_TokenSource_index[i]:_TokenSource_index[i+1]]
}
