// Code generated by "stringer -type=Version version.go"; DO NOT EDIT.

package validate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[V1-1]
	_ = x[V2-2]
}

const _Version_name = "V1V2"

var _Version_index = [...]uint8{0, 2, 4}

func (i Version) String() string {
	i -= 1
	if i < 0 || i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
