// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeProject-0]
	_ = x[TypeMod-1]
	_ = x[TypeService-2]
	_ = x[TypeBiz-3]
	_ = x[TypeDal-4]
}

const _Type_name = "ProjectModServiceBizDal"

var _Type_index = [...]uint8{0, 7, 10, 17, 20, 23}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
