// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from errors.go.

// Package errors contains generated code by adptool.
package errors

import (
	stderr "errors"

	merr "github.com/hashicorp/go-multierror"
	perr "github.com/pkg/errors"
)

var ErrUnsupported = stderr.ErrUnsupported

type (
	MultiError           = merr.Error
	MultiErrorFormatFunc = merr.ErrorFormatFunc
	MultiGroup           = merr.Group
	Frame                = perr.Frame
	StackTrace           = perr.StackTrace
)

func As(err error, target any) bool {
	return stderr.As(err, target)
}

func Is(err, target error) bool {
	return stderr.Is(err, target)
}

func Join(errs ...error) error {
	return stderr.Join(errs...)
}

func NewStdError(text string) error {
	return stderr.New(text)
}

func Unwrap(err error) error {
	return stderr.Unwrap(err)
}

func MultiAppend(err error, errs ...error) *merr.Error {
	return merr.Append(err, errs...)
}

func MultiFlatten(err error) error {
	return merr.Flatten(err)
}

func MultiListFormatFunc(es []error) string {
	return merr.ListFormatFunc(es)
}

func MultiPrefix(err error, prefix string) error {
	return merr.Prefix(err, prefix)
}

func AsPkgError(err error, target interface{}) bool {
	return perr.As(err, target)
}

func Cause(err error) error {
	return perr.Cause(err)
}

func Errorf(format string, args ...interface{}) error {
	return perr.Errorf(format, args...)
}

func IsPkgError(err, target error) bool {
	return perr.Is(err, target)
}

func New(message string) error {
	return perr.New(message)
}

func UnwrapPkgError(err error) error {
	return perr.Unwrap(err)
}

func WithMessage(err error, message string) error {
	return perr.WithMessage(err, message)
}

func WithMessagef(err error, format string, args ...interface{}) error {
	return perr.WithMessagef(err, format, args...)
}

func WithStack(err error) error {
	return perr.WithStack(err)
}

func Wrap(err error, message string) error {
	return perr.Wrap(err, message)
}

func Wrapf(err error, format string, args ...interface{}) error {
	return perr.Wrapf(err, format, args...)
}
