// Code generated by "stringer -type=AuthScheme -trimprefix=AuthScheme"; DO NOT EDIT.

package authenticate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthSchemeAnonymous-0]
	_ = x[AuthSchemeBasic-1]
	_ = x[AuthSchemeBearer-2]
	_ = x[AuthSchemeDigest-3]
	_ = x[AuthSchemeHOBA-4]
	_ = x[AuthSchemeMutual-5]
	_ = x[AuthSchemeNegotiate-6]
	_ = x[AuthSchemeVapid-7]
	_ = x[AuthSchemeSCRAM-8]
	_ = x[AuthSchemeAWS4HMAC256-9]
	_ = x[AuthSchemeDPoP-10]
	_ = x[AuthSchemeGNAP-11]
	_ = x[AuthSchemePrivate-12]
	_ = x[AuthSchemeOAuth-13]
	_ = x[AuthSchemeUnknown-14]
	_ = x[authSchemeMax-15]
}

const _AuthScheme_name = "AnonymousBasicBearerDigestHOBAMutualNegotiateVapidSCRAMAWS4HMAC256DPoPGNAPPrivateOAuthUnknownauthSchemeMax"

var _AuthScheme_index = [...]uint8{0, 9, 14, 20, 26, 30, 36, 45, 50, 55, 66, 70, 74, 81, 86, 93, 106}

func (i AuthScheme) String() string {
	if i < 0 || i >= AuthScheme(len(_AuthScheme_index)-1) {
		return "AuthScheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthScheme_name[_AuthScheme_index[i]:_AuthScheme_index[i+1]]
}
