// Code generated by "stringer -type=Type"; DO NOT EDIT.

package codec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JSON-0]
	_ = x[YAML-1]
	_ = x[TOML-2]
	_ = x[XML-3]
	_ = x[INI-4]
	_ = x[UNKNOWN-5]
}

const _Type_name = "JSONYAMLTOMLXMLINIUNKNOWN"

var _Type_index = [...]uint8{0, 4, 8, 12, 15, 18, 25}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
