name: Auto Tagging Submodule After Release

on:
  release:
    types: [ created ]
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  tag_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0 # v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history

      - name: Run tag script
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          chmod +x ./.github/scripts/tag.sh
          ./.github/scripts/tag.sh

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload assets
#        uses: actions/upload-artifact@v4.4.3
#        with:
#          name: protoc-gen-go-gins
#          path: ./cmd/protoc-gen-go-gins/dist/*
