// Code generated by "stringer -type=MethodType -trimprefix=Method"; DO NOT EDIT.

package filter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethodAny-0]
	_ = x[MethodGet-1]
	_ = x[MethodPut-2]
	_ = x[MethodDelete-3]
	_ = x[MethodConnect-4]
	_ = x[MethodHead-5]
	_ = x[MethodPost-6]
	_ = x[MethodPatch-7]
	_ = x[MethodTrace-8]
	_ = x[MethodOptions-9]
	_ = x[MethodTypeMax-10]
}

const _MethodType_name = "AnyGetPutDeleteConnectHeadPostPatchTraceOptionsTypeMax"

var _MethodType_index = [...]uint8{0, 3, 6, 9, 15, 22, 26, 30, 35, 40, 47, 54}

func (i MethodType) String() string {
	if i >= MethodType(len(_MethodType_index)-1) {
		return "MethodType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MethodType_name[_MethodType_index[i]:_MethodType_index[i+1]]
}
