name: Release on Tag

on:
  push:
    tags:
      - 'v*' # Trigger only on tags that start with 'v'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'

      - name: Run tests
        # Use the ci.sh script to run tests for all modules
        run: |
          chmod +x ./.github/scripts/ci.sh
          ./.github/scripts/ci.sh test

  create-release:
    # This job runs only after the 'test' job succeeds
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        # This action automatically uses the pushed tag (e.g., v1.2.3) to create a release
        # It also auto-generates a changelog with relevant commits
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
