name: Test and Release

# This workflow runs on every push to the main branch.
# It always runs tests. A release is only triggered if the commit message
# contains the string "[release]".
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.23.0'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.23.0' # The Go version to download (if necessary) and use.

      - name: Run tests
        run: make test

  release:
    # The release job depends on the test job succeeding. Ensure lint and test pass before releasing.
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release and Changelog
        id: release # 添加 ID 以便引用输出
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: If you want to do something after a release is created (e.g., notify Slack)
      - name: Notify on new release
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          echo "New release created: ${{ steps.release.outputs.tag_name }}"
          echo "Release notes: ${{ steps.release.outputs.release_notes }}"
          # Add your notification logic here (e.g., curl to Slack webhook)
